### ISSUE TITLE
A Question About ProcessSlice

### ISSUE THREAD

**Issue by kira8565** [viant/toolbox#1]
The Comment Of `ProcessSlice` is ProcessSlice iterates over any slice, it calls handler with each element unless handler returns false. But I found No mater What the handle function retue .the result is same 

```
	aSlice := []interface{}{
		"abc", "def", "cyz", "adc",
	}

	count := 0
	toolbox.ProcessSlice(aSlice, func(item interface{}) bool {
		count++
		return false
	})

	println(count)
```

in this sample i set the return value is false ,But the value `count` is 4  not 1, Is my understanding of this is wrong?

**Comment by adranwit** [comment]
Description is correct, I have introduced bug while providing optimization for []string slice, 
I have patched the code and added negative use cases
