### ISSUE TITLE
IsCompleteJSON returns false for strings

### ISSUE THREAD

**Issue by pallavJha** [viant/toolbox#19]
The function, `IsCompleteJSON`, returns `false` when the input is `"abc"`. However, Go's `json.Valid()` returns `true` for the same.

https://github.com/viant/toolbox/blob/5994d07d8d5cd079b2ac2ca2d0ca14f9ab6a268f/json.go#L13

**Comment by adranwit** [comment]
The original intention of that function was to check if a text is complete JSON structure  (map or array), as opposed to a primitive JSON value
I guess the devil is in the details, 

Would renaming IsCompleteJSON to IsStructuredJSON address your concern?

**Comment by pallavJha** [comment]
Yes, it would do. Now, the caller of the function must know the difference between structured and primitive JSON.

**Comment by adranwit** [comment]
addressed in https://github.com/viant/toolbox/releases/tag/v0.24.0
