### ISSUE TITLE
paths are wrong on windows

### ISSUE THREAD

**Issue by langohr** [viant/toolbox#22]
If you are using this toolbox with windows the path are not correct.

The reason is, that you are using 
  import "path"
instead of 
  import "path/filepath"

could you change fileset_info.go line 488 to

`filename := filepath.Base(filename)`

and add the import

`  import "path/filepath"`

**Comment by langohr** [comment]
@adranwit Could you please fix that?

**Comment by adranwit** [comment]
Please let me know if a patch worked for you, otherwise, I will close the issue in 24 hours,
