### ISSUE TITLE
Circular dependency issues

### ISSUE THREAD

**Issue by creekorful** [viant/toolbox#26]
Hello there!

I was packaging your library on Debian since it's needed as dependency for another package, and I have noticed a cyclic dependency between viant/toolbox and viant/afs.

### resource.go

```golang
"github.com/viant/afs/option"

[...]

CustomKey       *option.AES256Key `description:" content encryption key"`
```

### ignore.go

```golang
"github.com/viant/toolbox"

[...]

for _, item := range strings.Split(toolbox.AsString(content), "\n") {
```
### info.go

```golang
"github.com/viant/toolbox/storage"

[...]

mode = storage.DefaultFileMode
```

I would like to know if you are interested to fix this.

**Comment by adranwit** [comment]
Thanks for bringing it up, I'll fix it

**Comment by creekorful** [comment]
Thank you! While I'm here, there is the same issue between viant/afs & viant/afsc, I can open another issue if you want.

**Comment by adranwit** [comment]
I've updated viant/afs, viant/toolbox,viant/endly with refactored dep, 
Thanks again,
