### ISSUE TITLE
Wrong permissions on storage/* files

### ISSUE THREAD

**Issue by creekorful** [viant/toolbox#27]
Hello back!

I have noticed that the following files have wrong permissions.

```
toolbox/storage/file_service.go
toolbox/storage/gs/object.go
toolbox/storage/gs/service.go
toolbox/storage/http_service.go
toolbox/storage/http_service_test.go
toolbox/storage/object.go
toolbox/storage/scp/object.go
toolbox/storage/scp/service.go
toolbox/storage/service.go
toolbox/storage/service_test.go
```

Permissions is set to 0755 (executable bit set) where it should be 0644 (like your other files).

A simple chmod -R 644 storage/*.go should do the trick.

**Comment by adranwit** [comment]
Thanks again, just patched permission, 

btw. note that toolbox/storage/ is deprecated - 
please use https://github.com/viant/afs API instead

**Comment by creekorful** [comment]
Hello,

Sure thank you! 
I'm not using toolbox/storage API, but since I'm making viant/toolbox as a Debian package, the whole APIs will be packaged.

The following files still have wrong permissions:

```
toolbox/storage/gs/object.go
toolbox/storage/gs/service.go
toolbox/storage/scp/object.go
toolbox/storage/scp/service.go
```

It's my fault, the appropriate command would be ``chmod -R 644 storage/*/*.go``

**Comment by adranwit** [comment]
Thanks again, patched
