### ISSUE TITLE
TestWaitTimeout_TimeoutTriggered fails at go test

### ISSUE THREAD

**Issue by rogers0** [viant/toolbox#28]
Hi there,

I'm working with @creekorful to package this project into Debian.
Debian build system usually run go test after building the package, so I find TestWaitTimeout_TimeoutTriggered fails, whatever has network access.
Here's the log:

```
=== RUN   TestWaitTimeout_TimeoutTriggered
    TestWaitTimeout_TimeoutTriggered: waitgroup_helper_test.go:19:
                Error Trace:    waitgroup_helper_test.go:19
                Error:          Not equal:
                                expected: true
                                actual  : false
                Test:           TestWaitTimeout_TimeoutTriggered
--- FAIL: TestWaitTimeout_TimeoutTriggered (0.00s)
```

**Comment by adranwit** [comment]
patched issue

**Comment by rogers0** [comment]
I'm sorry that this issue still occurs on version 0.32.2, but just sometimes.
(Yes, sometimes it can pass.)
Here's the log when it fails:
```
=== RUN   TestWaitTimeout_TimeoutTriggered
    TestWaitTimeout_TimeoutTriggered: waitgroup_helper_test.go:20:
                Error Trace:    waitgroup_helper_test.go:20
                Error:          Not equal:
                                expected: true
                                actual  : false
                Test:           TestWaitTimeout_TimeoutTriggered
--- FAIL: TestWaitTimeout_TimeoutTriggered (0.00s)
```

**Comment by rogers0** [comment]
could you kindly reopen this ticket?
thank you!

**Comment by rogers0** [comment]
I confirm this issue, TestWaitTimeout_TimeoutTriggered, still fails sometimes on latest 0.33.0
although I disabled this test, so it won't shown on reproducible builds.
- debian patch: https://salsa.debian.org/go-team/packages/golang-github-viant-toolbox/-/blob/debian/sid/debian/patches/0001-Skip-some-tests-fail-at-git-pbuilder-environment.patch

**Comment by adranwit** [comment]
Patched race condition

**Comment by rogers0** [comment]
@adranwit Thanks!
I confirmed by [ad4995d] the test can be passed, on 0.33.0-9.
- https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/golang-github-viant-toolbox.html

So closing this ticket.
