### ISSUE TITLE
fileset_info_test/user_func.go build error

### ISSUE THREAD

**Issue by rogers0** [viant/toolbox#32]
error message:
src/github.com/viant/toolbox/fileset_info_test/user_func.go:6:10: undefined: User

**Comment by rogers0** [comment]
so I need this patch for debian packaging:
- https://salsa.debian.org/go-team/packages/golang-github-viant-toolbox/-/blob/debian/sid/debian/patches/0001-Fix-test-in-fileset_info_test.patch

**Comment by adranwit** [comment]
reorganized test data

**Comment by rogers0** [comment]
Confirmed it's fixed. Thank you!
