### ISSUE TITLE
TestService_List fails at go test

### ISSUE THREAD

**Issue by rogers0** [viant/toolbox#36]
TestService_List usually passes, but it fails on reproducible builds:
- https://tests.reproducible-builds.org/debian/rbuild/unstable/arm64/golang-github-viant-toolbox_0.32.2-1.rbuild.log.gz
- https://tests.reproducible-builds.org/debian/rbuild/unstable/armhf/golang-github-viant-toolbox_0.32.2-1.rbuild.log.gz

error log for version 0.32.2:
```
=== RUN   TestService_List
    TestService_List: service_test.go:23: 
        	Error Trace:	service_test.go:23
        	Error:      	Expected nil, but got: &os.PathError{Op:"open", Path:"/nonexistent", Err:0x2}
        	Test:       	TestService_List
--- FAIL: TestService_List (0.00s)
```

**Comment by adranwit** [comment]
updated test

**Comment by rogers0** [comment]
Confirmed it's fixed. Thank you!

**Comment by rogers0** [comment]
Sorry, this still occurs on latest.
I have to reopen this ticket.

https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/golang-github-viant-toolbox_0.32.3-1.rbuild.log.gz

log:
```
=== RUN   TestService_List
    TestService_List: service_test.go:23: 
        	Error Trace:	service_test.go:23
        	Error:      	Expected nil, but got: &os.PathError{Op:"open", Path:"/nonexistent", Err:0x2}
        	Test:       	TestService_List
--- FAIL: TestService_List (0.00s)
```

**Comment by rogers0** [comment]
For latest 0.33.0, the result seems the same.
- https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/golang-github-viant-toolbox_0.33.0-1.rbuild.log.gz

**Comment by adranwit** [comment]
commented test as deprecated

**Comment by rogers0** [comment]
thanks for your support!
closing this ticket.
