### ISSUE TITLE
Circular dependency viant/toolbox <-> viant/assertly

### ISSUE THREAD

**Issue by creekorful** [viant/toolbox#38]
Hello! Hope you are doing fine.

While I was packaging your library for Debian with @rogers0 we have identified a circular dependency
between this library and viant/assertly.
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963851

If you consider it, this circular dependency could be easily fixed since only 2 tests are using assertly.
See: https://github.com/viant/toolbox/search?q=viant%2Fassertly&unscoped_q=viant%2Fassertly

What do you think?

**Comment by adranwit** [comment]
Removed dependencies

**Comment by creekorful** [comment]
Thank you!
