### ISSUE TITLE
DateFormatToLayout does not work as expected

### ISSUE THREAD

**Issue by bhj666** [viant/toolbox#42]
Hi, I recently used this library for time parsing, and noticed strange error with DateFormatToLayout. It returns "2006-01-02 05:04:05" instead of "2006-01-02 15:04:05" which causes bug. Please check this code sample https://go.dev/play/p/uGKxa8vCsfH

**Comment by adranwit** [comment]
If you see error parsing:
parsing time "2022-01-11 18:16:33": hour out of range0001-01-01 00:00:00 +0000 UTC
2022-01-11 18:16:33 +0000 UTC

The reason of the exception is that you have used lowercase 'hh' (0-12 hours only), vs HH that is 0-23
